cargo-features = ["resolver"]

[workspace]
exclude = ["substrate"]
members = [
	"cli",
	"executor",
	"primitives",
	"rpc",
	"pallets/did",
	"pallets/ads",
	"runtime",
]

resolver = "2"

[profile.release]
# Substrate runtime requires unwinding.
panic = "unwind"
